/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OptimizationSuggestionService } from "../optimizationSuggestion.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OptimizationSuggestionCreateInput } from "./OptimizationSuggestionCreateInput";
import { OptimizationSuggestion } from "./OptimizationSuggestion";
import { OptimizationSuggestionFindManyArgs } from "./OptimizationSuggestionFindManyArgs";
import { OptimizationSuggestionWhereUniqueInput } from "./OptimizationSuggestionWhereUniqueInput";
import { OptimizationSuggestionUpdateInput } from "./OptimizationSuggestionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OptimizationSuggestionControllerBase {
  constructor(
    protected readonly service: OptimizationSuggestionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OptimizationSuggestion })
  @nestAccessControl.UseRoles({
    resource: "OptimizationSuggestion",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createOptimizationSuggestion(
    @common.Body() data: OptimizationSuggestionCreateInput
  ): Promise<OptimizationSuggestion> {
    return await this.service.createOptimizationSuggestion({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        savingsAmount: true,
        priority: true,
        relatedExpense: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OptimizationSuggestion] })
  @ApiNestedQuery(OptimizationSuggestionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OptimizationSuggestion",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async optimizationSuggestions(
    @common.Req() request: Request
  ): Promise<OptimizationSuggestion[]> {
    const args = plainToClass(
      OptimizationSuggestionFindManyArgs,
      request.query
    );
    return this.service.optimizationSuggestions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        savingsAmount: true,
        priority: true,
        relatedExpense: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OptimizationSuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OptimizationSuggestion",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async optimizationSuggestion(
    @common.Param() params: OptimizationSuggestionWhereUniqueInput
  ): Promise<OptimizationSuggestion | null> {
    const result = await this.service.optimizationSuggestion({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        savingsAmount: true,
        priority: true,
        relatedExpense: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OptimizationSuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OptimizationSuggestion",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateOptimizationSuggestion(
    @common.Param() params: OptimizationSuggestionWhereUniqueInput,
    @common.Body() data: OptimizationSuggestionUpdateInput
  ): Promise<OptimizationSuggestion | null> {
    try {
      return await this.service.updateOptimizationSuggestion({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          savingsAmount: true,
          priority: true,
          relatedExpense: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OptimizationSuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OptimizationSuggestion",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOptimizationSuggestion(
    @common.Param() params: OptimizationSuggestionWhereUniqueInput
  ): Promise<OptimizationSuggestion | null> {
    try {
      return await this.service.deleteOptimizationSuggestion({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          savingsAmount: true,
          priority: true,
          relatedExpense: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
