/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SavingsStatisticsService } from "../savingsStatistics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SavingsStatisticsCreateInput } from "./SavingsStatisticsCreateInput";
import { SavingsStatistics } from "./SavingsStatistics";
import { SavingsStatisticsFindManyArgs } from "./SavingsStatisticsFindManyArgs";
import { SavingsStatisticsWhereUniqueInput } from "./SavingsStatisticsWhereUniqueInput";
import { SavingsStatisticsUpdateInput } from "./SavingsStatisticsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SavingsStatisticsControllerBase {
  constructor(
    protected readonly service: SavingsStatisticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SavingsStatistics })
  @nestAccessControl.UseRoles({
    resource: "SavingsStatistics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSavingsStatistics(
    @common.Body() data: SavingsStatisticsCreateInput
  ): Promise<SavingsStatistics> {
    return await this.service.createSavingsStatistics({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        timePeriod: true,
        totalSavings: true,
        optimizationLevel: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SavingsStatistics] })
  @ApiNestedQuery(SavingsStatisticsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SavingsStatistics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savingsStatisticsItems(
    @common.Req() request: Request
  ): Promise<SavingsStatistics[]> {
    const args = plainToClass(SavingsStatisticsFindManyArgs, request.query);
    return this.service.savingsStatisticsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        timePeriod: true,
        totalSavings: true,
        optimizationLevel: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SavingsStatistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsStatistics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savingsStatistics(
    @common.Param() params: SavingsStatisticsWhereUniqueInput
  ): Promise<SavingsStatistics | null> {
    const result = await this.service.savingsStatistics({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        timePeriod: true,
        totalSavings: true,
        optimizationLevel: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SavingsStatistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsStatistics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSavingsStatistics(
    @common.Param() params: SavingsStatisticsWhereUniqueInput,
    @common.Body() data: SavingsStatisticsUpdateInput
  ): Promise<SavingsStatistics | null> {
    try {
      return await this.service.updateSavingsStatistics({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          timePeriod: true,
          totalSavings: true,
          optimizationLevel: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SavingsStatistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsStatistics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSavingsStatistics(
    @common.Param() params: SavingsStatisticsWhereUniqueInput
  ): Promise<SavingsStatistics | null> {
    try {
      return await this.service.deleteSavingsStatistics({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          timePeriod: true,
          totalSavings: true,
          optimizationLevel: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
